del %1Diacritics.dll
del %1Emby.Naming.dll
del %1ICU4N.dll
del %1ICU4N.Transliterator.dll
del %1J2N.dll
del %1Jellyfin.Data.dll
del %1MediaBrowser.Common.dll
del %1MediaBrowser.Controller.dll
del %1MediaBrowser.Model.dll
del %1Microsoft.Bcl.TimeProvider.dll
del %1Microsoft.Extensions.Configuration.Binder.dll
del %1Microsoft.Extensions.DependencyInjection.Abstractions.dll
del %1Microsoft.Extensions.DependencyInjection.dll
del %1Microsoft.Extensions.Logging.Abstractions.dll
del %1Microsoft.Extensions.Options.dll
del %1Jellyfin.Extensions.dll
del %1Microsoft.Extensions.Logging.dll