---
name: "CFAuth"
guid: "09edc1d4-b95a-464b-8059-ae6b5f5daa93"
version: "1.1.0.0"
targetAbi: "10.10.1.0"
framework: "net8.0"
overview: "Cloudflared Access Authentication"
description: >
  A plugin that reads and validates JSON Web Tokens.
  Specifically for Cloudflare Access and their tunneling.
category: "Authentication"
owner: "RedNoodles"
artifacts:
- "Jellyfin.Plugin.CFAuth.dll"
- "Microsoft.IdentityModel.Abstractions.dll"
- "Microsoft.IdentityModel.JsonWebTokens.dll"
- "Microsoft.IdentityModel.Logging.dll"
- "Microsoft.IdentityModel.Tokens.dll"
- "System.IdentityModel.Tokens.Jwt.dll"
changelog: >
 - Refactor code: 1.1.0.0
 - Initial release: 1.0.0.0

